python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 0 --end_sample_id 500 --device 0 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 500 --end_sample_id 1000 --device 0 & 
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 1000 --end_sample_id 1500 --device 0 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 1500 --end_sample_id 2000 --device 0 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 2000 --end_sample_id 2500 --device 0 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 2500 --end_sample_id 3000 --device 1 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 3000 --end_sample_id 3500 --device 1 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 3500 --end_sample_id 4000 --device 1 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 4000 --end_sample_id 4500 --device 1 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 4500 --end_sample_id 5000 --device 1 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 5000 --end_sample_id 5500 --device 2 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 5500 --end_sample_id 6000 --device 2 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 6000 --end_sample_id 6500 --device 2 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 6500 --end_sample_id 7000 --device 2 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 7000 --end_sample_id 7500 --device 2 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 7500 --end_sample_id 8000 --device 3 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 8000 --end_sample_id 8500 --device 3 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 8500 --end_sample_id 9000 --device 3 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 9000 --end_sample_id 9500 --device 3 &
python3 run_multiple_detect.py --node_id 24 --data_folder unlabel_data --start_sample_id 9500 --end_sample_id 10000 --device 3 &